---
title: "bootstraping"
author: "Longyi Zhao"
date: "2023-11-16"
output: github_document
---
```{r}
library(tidyverse)
library(modelr)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6, 
  out.width = "90%"
)

theme_set (theme_minimal() +theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis", 
  ggplots.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_disrete = scale_fill_viridis_d

set.seed(1)
```


## generate a relevant example

```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst = sim_df_const |> 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)

sim_df_const |>
  ggplot(aes(x = x, y = y)) + geom_point()
```

fit some linear models
```{r}
sim_df_const|>
  lm(y~x, data = _) |>
  broom::tidy()

sim_df_nonconst|>
  lm(y~x, data=_) |>
  broom::tidy()
# data is not supposed to look at that, still want to extract informaiton from it?
```

## Draw and analyze a bootstrap sample

start with a little function 
```{r}
boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}
```

Lets see how this works

```{r}
sim_df_nonconst |> 
  boot_sample() |>
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm")

# different degree of shading for points, picking the same thing several times, get darker points. 
```

## Draw a lot of samples and analyze them 

```{r}
boot_straps = 
  tibble(strap_number = 1:100) |> 
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(df = sim_df_nonconst))
  )

boot_straps |>
  pull(strap_sample) |>
  nth(2) |>
  arrange(x)
```

now do the lm fit
```{r}
boot_results =
  boot_straps|>
  mutate(models = map(strap_sample, \(df) lm(y~x, data = df)), 
         results = map(models, broom::tidy)
  ) |>
  select(strap_number, results) |>
  unnest(results)


# fit a correspond linear model to all of these
```














