---
title: "linear_models"
author: "Longyi Zhao"
date: "2023-11-09"
output: github_document
---
```{r}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6, 
  out.width = "90%"
)

theme_set (theme_minimal() +theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis", 
  ggplots.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_disrete = scale_fill_viridis_d

set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |>
  mutate(stars = review_scores_location/2) |>
  select(
    price, stars, borough = neighbourhood_group, 
    neighbourhood, room_type) |>
  filter(borough != "Staten Island")
```

Let's fit a model!!
```{r}
fit = lm(price ~ stars +borough, data = nyc_airbnb)
```

```{r}
fit = nyc_airbnb |>
  lm(price~stars + borough, data = _)
```

take a look at the fit by using summary(fit) in the console
Not very useful methods
```{r}
# summary(fit)
# summary(fit)$coef
# coef(fit)
# fitted.values(fit)
```

tidy up the output instead
```{r}
fit |>
  broom::glance()
```

tidy up the coefficient, this is more useful 
```{r}
fit |>
  broom::tidy() |>
  mutate(term = str_replace(term, "^borough", "Borough: ")) |>
  select(term, estimate, p.value) |>
  knitr::kable(digits = 3)
```




















